# Generated by Django 4.2.2 on 2023-07-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakhi', '0002_registration_email_registration_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
